/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop;


import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JCalendar;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Mahmudul Hasan
 */
public class SalesCollection extends javax.swing.JFrame {

    /**
     * Creates new form SalesCollection
     */
    public SalesCollection() {
        initComponents();
        lbDate.setText(lDate);
        txtCustomer.requestFocus();
    }
    //Custom Variables
    java.sql.Connection con = null;
    java.sql.Statement st = null;
    ResultSet rs = null;
    String url = "jdbc:mysql://localhost:3306/javatest";
    String un = "root";
    String pw = "";
   static String myBill="";
    
    JCalendar jc=new JCalendar();
    SimpleDateFormat sm=new SimpleDateFormat("yyyy-MM-dd");
    String lDate=sm.format(jc.getDate());
    //Custom Methods
    void dbConnect() {

        try {
            con = DriverManager.getConnection(url, un, pw);
            st = con.createStatement();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(SalesData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    void showData(String query){
        try {
            dbConnect();
            DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            double totalDisc=0;
            double totalAmount=0;
            double totalPaid=0;
            rs=st.executeQuery(query);
            for (double i=0; rs.next(); ) {
                double d;
                double t;
                double p;
                d=rs.getDouble(6);
                t=rs.getDouble(5);
                p=rs.getDouble(7);
                lbName.setText(rs.getString(2));
                i=rs.getDouble(8);
                totalDisc=totalDisc+d;
                totalAmount=totalAmount+t;
                totalPaid=totalPaid+p;
            dtm.addRow(new Object[]{rs.getString(1),rs.getString(3),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
            }
           Double totalDue1=totalAmount-totalPaid-totalDisc;
            txtTotalDue.setText(""+totalDue1);
            lbDiscount.setText(""+totalDisc);
            lbAmount.setText(""+totalAmount);
            lbPaid.setText(""+totalPaid);
        } catch (SQLException ex) {
            Logger.getLogger(SalesData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    String lastBill(){String b="";
    try {
        dbConnect();
        
        String ls="SELECT * FROM `salescollection` WHERE `Customer Name`='"+txtCustomer.getText()+"'";
        rs=st.executeQuery(ls);
        if(rs.last()){
            b=rs.getString(1);
        }
                } catch (SQLException ex) {
            Logger.getLogger(SalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }
    return b;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbName = new javax.swing.JLabel();
        lbPaid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        txtTotalDue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbDate = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFind = new javax.swing.JButton();
        txtCustomer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Collection");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No.", "Date", "Amount", "Discount", "Paid", "Due"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 1110, 330);

        lbName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbName);
        lbName.setBounds(120, 0, 180, 40);

        lbPaid.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbPaid.setForeground(new java.awt.Color(255, 255, 255));
        lbPaid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPaid.setText("total paid");
        jPanel1.add(lbPaid);
        lbPaid.setBounds(740, 380, 180, 20);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Paid");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(890, 450, 70, 40);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 0, 60, 40);

        txtPaid.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
        });
        jPanel1.add(txtPaid);
        txtPaid.setBounds(970, 450, 130, 40);

        txtTotalDue.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTotalDue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtTotalDue);
        txtTotalDue.setBounds(970, 400, 130, 40);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Name:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 0, 80, 40);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Total Due:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(870, 400, 100, 40);

        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Submit Paid");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 440, 180, 50);

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 440, 160, 50);

        jButton3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 440, 160, 50);

        lbDate.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbDate.setForeground(new java.awt.Color(255, 255, 255));
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDate.setText("date");
        jPanel1.add(lbDate);
        lbDate.setBounds(620, 0, 170, 40);

        lbAmount.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbAmount.setForeground(new java.awt.Color(255, 255, 255));
        lbAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAmount.setText("total amount");
        jPanel1.add(lbAmount);
        lbAmount.setBounds(380, 380, 180, 20);

        lbDiscount.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lbDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiscount.setText("total discount");
        jPanel1.add(lbDiscount);
        lbDiscount.setBounds(570, 380, 180, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 1110, 510);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        btnFind.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel2.add(btnFind);
        btnFind.setBounds(760, 10, 130, 40);

        txtCustomer.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFocusLost(evt);
            }
        });
        txtCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCustomerMouseClicked(evt);
            }
        });
        txtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerActionPerformed(evt);
            }
        });
        txtCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerKeyPressed(evt);
            }
        });
        jPanel2.add(txtCustomer);
        txtCustomer.setBounds(360, 10, 390, 40);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Customer Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 10, 180, 40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Go Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 70, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1110, 70);

        setSize(new java.awt.Dimension(1110, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        //Find
        if(!txtCustomer.getText().isEmpty()){
        String name=txtCustomer.getText();
        String query="SELECT * FROM `salescollection` WHERE `Customer Name`='"+name+"'";
        dbConnect();
        showData(query);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerFocusLost
        // TODO add your handling code here:
         if(!txtCustomer.getText().isEmpty()){
        String query="SELECT * FROM `salescollection` WHERE `Customer Name`='"+txtCustomer.getText()+"'";
        dbConnect();
        showData(query);
        }
    }//GEN-LAST:event_txtCustomerFocusLost

    private void txtCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtCustomerFocusGained

    private void txtCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerKeyPressed
        // :
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        if(!txtCustomer.getText().isEmpty()){
        String name=txtCustomer.getText();
        String query="SELECT * FROM `salescollection` WHERE `Customer Name`='"+name+"'";
        dbConnect();
        showData(query);
        }
        }
    }//GEN-LAST:event_txtCustomerKeyPressed

    private void txtCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCustomerMouseClicked
        // TODO add your handling code here:
        txtCustomer.setText("");
    }//GEN-LAST:event_txtCustomerMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int exit=JOptionPane.showConfirmDialog(this, "Are you sure?","Exit",JOptionPane.YES_NO_OPTION);
        if(exit==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!txtPaid.getText().isEmpty()){
        try {
            // Submit Paid:
            dbConnect();
            String paid1=txtPaid.getText();
            Double due1=Double.parseDouble(txtTotalDue.getText());
            double tDue=due1-Double.parseDouble(txtPaid.getText());
            String bill1=lastBill()+txtCustomer.getText();
            String sq="INSERT INTO `salescollection` VALUES('"+bill1+"','"+txtCustomer.getText()+"','"+lbDate.getText()+"','"+0+"','"+0+"','"+0+"','"+paid1+"','"+tDue+"')";
            int submit=st.executeUpdate(sq);
            if(submit>0){
                JOptionPane.showMessageDialog(this, "Submitted Successfully!!");
                String query="SELECT * FROM `salescollection` WHERE `Customer Name`='"+txtCustomer.getText()+"'";
                showData(query);   
            }
        } catch (SQLException ex) {
            Logger.getLogger(SalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed
        //
        if(!txtPaid.getText().isEmpty()){
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            // Submit Paid:
            dbConnect();
            String paid1=txtPaid.getText();
            Double due1=Double.parseDouble(txtTotalDue.getText());
            double tDue=due1-Double.parseDouble(txtPaid.getText());
            String bill1=lastBill()+txtCustomer.getText();
            String sq="INSERT INTO `salescollection` VALUES('"+bill1+"','"+txtCustomer.getText()+"','"+lbDate.getText()+"','"+0+"','"+0+"','"+0+"','"+paid1+"','"+tDue+"')";
            int submit=st.executeUpdate(sq);
            if(submit>0){
                JOptionPane.showMessageDialog(this, "Submitted Successfully!!");
                String query="SELECT * FROM `salescollection` WHERE `Customer Name`='"+txtCustomer.getText()+"'";
                showData(query);   
            }
        } catch (SQLException ex) {
            Logger.getLogger(SalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }
        }}
    }//GEN-LAST:event_txtPaidKeyPressed

    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            jTable1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(SalesCollection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesCollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPaid;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtTotalDue;
    // End of variables declaration//GEN-END:variables
}
